/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<STM32F407xx.h>
void delay_ms(uint32_t time){
    while(time--){
        for(volatile int i = 0; i < 1680; i++);
    }
}
static uint8_t Count=0;
class ButtonObserver
{
public:
    virtual void onButtonPressed() = 0;
};

/* ---------------- SUBJECT (BUTTON) ---------------- */
class Button
{
    GPIO_TypeDef* port;
    uint16_t pin;

    ButtonObserver* observers[10];
    int count;

public:
    Button(GPIO_TypeDef* p, uint16_t pin)
        : port(p), pin(pin), count(0) {}

    void attach(ButtonObserver* obs)
    {
        if(count < 10)
            observers[count++] = obs;
    }

    int read()
    {
        return (port->IDR & pin) ? 1 : 0;
    }


    void poll()
    {
        int currentState = read();
        static uint32_t prevState=0;

        if (currentState == 1 && prevState == 0)
        {
            delay_ms(20);                             // debounce wait

            if (read() == 1){
            	Count++;
                notify();
            }
        }

        prevState = currentState;
    }

private:
    void notify()
    {
        for(int i = 0; i < count; i++)
        {
            observers[i]->onButtonPressed();
        }
    }
};

/* ---------------- LED OBSERVER ---------------- */
class LED_Green : public ButtonObserver
{
    GPIO_TypeDef* port;
    uint16_t pin;

public:
    LED_Green(GPIO_TypeDef* p, uint16_t pin)
        : port(p), pin(pin) {}

    void onButtonPressed() override
    {
        if(port->ODR & pin)
        {
            port->BSRR = (pin << 16);  // Reset
        }
        else
        {
            port->BSRR = pin;          // Set
        }
    }
};
class LED_Orange : public ButtonObserver
{
    GPIO_TypeDef* port;
    uint16_t pin;

public:
    LED_Orange(GPIO_TypeDef* p, uint16_t pin)
        : port(p), pin(pin) {}

    void onButtonPressed() override
    {
    	if(Count%2==0){
        if(port->ODR & pin)
        {
            port->BSRR = (pin << 16);  // Reset
        }
        else
        {
            port->BSRR = pin;          // Set
        }
    	}
    }
};
class LED_Blue : public ButtonObserver
{
    GPIO_TypeDef* port;
    uint16_t pin;

public:
    LED_Blue(GPIO_TypeDef* p, uint16_t pin)
        : port(p), pin(pin) {}

    void onButtonPressed() override
    {
       /* if(port->ODR & pin)
        {
            port->BSRR = (pin << 16);  // Reset
        }
        else
        {*/
            port->BSRR = pin;          // Set
    }
};
class LED_Red : public ButtonObserver
{
    GPIO_TypeDef* port;
    uint16_t pin;

public:
    LED_Red(GPIO_TypeDef* p, uint16_t pin)
        : port(p), pin(pin) {}

    void onButtonPressed() override
    {
        if(port->ODR & pin)
        {
            port->BSRR = (pin << 16);  // Reset
        }
        else
        {
            port->BSRR = pin;          // Set
        }
    }
};

/* ---------------- GPIO INIT ---------------- */
void GPIO_Init()
{
    // Enable GPIOA and GPIOD clock
    RCC->AHB1ENR |= (1 << 0); // GPIOA
    RCC->AHB1ENR |= (1 << 3); // GPIOD

    // PA0 → input
    GPIOA->MODER &= ~(3 << (0 * 2));

    // PD12–PD15 → output
    for(int i = 12; i <= 15; i++)
    {
        GPIOD->MODER &= ~(3 << (i * 2));
        GPIOD->MODER |=  (1 << (i * 2));
    }
}

/* ---------------- MAIN ---------------- */
int main()
{
    GPIO_Init();

    // Subject
    Button button(GPIOA, (1 << 0));  // PA0

    // Observers (LEDs)- 4 objs
    LED_Green led1(GPIOD, (1 << 12));
    LED_Orange led2(GPIOD, (1 << 13));
    LED_Red led3(GPIOD, (1 << 14));
    LED_Blue led4(GPIOD, (1 << 15));

    // Attach observers
    button.attach(&led1);
    button.attach(&led2);
    button.attach(&led3);
    button.attach(&led4);

    while(1)
    {
        button.poll();

        // Small delay (basic debounce)
        for(volatile int i = 0; i < 100000; i++);
    }
}
