/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
int main(void){

int* pRCC_AHB1ENB=(int *) 0x40023830;
int* pGPIOD_MODER=(int *)0x40020C00;
int* pGPIOD_ODR= (int *)0x40020C14;

*pRCC_AHB1ENB |= (1 << 3);
*pGPIOD_MODER &= ~(3 << 24);
*pGPIOD_MODER |=  (1 << 24);
*pGPIOD_MODER &= ~(3 << 26);
*pGPIOD_MODER |=  (1 << 26);
*pGPIOD_MODER &= ~(3 << 28);
*pGPIOD_MODER |=  (1 << 28);
*pGPIOD_MODER &= ~(3 << 30);
*pGPIOD_MODER |=  (1 << 30);
while(1)
{
    *pGPIOD_ODR |= (1 << 12);
    for(int i = 0; i < 100000; i++);
    *pGPIOD_ODR &= ~(1 << 12);
    for(int i = 0; i < 100000; i++);
    *pGPIOD_ODR |= (1 << 13);
        for(int i = 0; i < 100000; i++);
        *pGPIOD_ODR &= ~(1 << 13);
        for(int i = 0; i < 100000; i++);
        *pGPIOD_ODR |= (1 << 14);
            for(int i = 0; i < 100000; i++);
            *pGPIOD_ODR &= ~(1 << 14);
            for(int i = 0; i < 100000; i++);
            *pGPIOD_ODR |= (1 << 15);
             for(int i = 0; i < 100000; i++);
            *pGPIOD_ODR &= ~(1 << 15);
            for(int i = 0; i < 100000; i++);
}
}
