/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"STM32F405xx.h"
#include<array>
class GPIOClockGuard
{
public:
    GPIOClockGuard()
    {
        RCC->AHB1ENR |= (1U << 3); // Enable GPIOD
        RCC->AHB1ENR |= (1U << 0); // Enable GPIOA
    }

    ~GPIOClockGuard()
    {
        RCC->AHB1ENR &= ~(1U << 3); // Disable GPIOD
        RCC->AHB1ENR &= ~(1U << 0); // Disable GPIOA
    }
};

// ==============================
//  GPIO Helper
// ==============================
class GPIO
{
public:
    static void set_output(volatile std::uint32_t& moder, std::uint32_t pin)
    {
        moder &= ~(3U << (pin * 2));
        moder |=  (1U << (pin * 2)); // Output mode
    }

    static void set_input(volatile std::uint32_t& moder, std::uint32_t pin)
    {
        moder &= ~(3U << (pin * 2)); // Input mode (00)
    }

    static void toggle(volatile std::uint32_t& odr, std::uint32_t pin)
    {
        odr ^= (1U << pin);
    }

    static bool read(volatile std::uint32_t& idr, std::uint32_t pin)
    {
        return (idr & (1U << pin));
    }
};

// ==============================
//  Delay
// ==============================
void delay()
{
    for (std::uint32_t i = 0; i < 100000; ++i)
    {
        // Prevent optimization
    }
}
int main(){
	//constexpr uint8_t LED_PIN=15;
	constexpr uint32_t Button_PIN=0;
	std::array<uint8_t,4>LED={12,13,14,15};
	{
		GPIOClockGuard g;
		for(auto &i:LED){
		GPIO::set_output(GPIOD->MODER,i);
		}
		GPIO::set_input(GPIOA->IDR,Button_PIN);
		while(true){
			if(GPIO::read(GPIOA->IDR,Button_PIN)){
				break;
			}
			for(auto& i:LED){
			GPIO::toggle(GPIOD->ODR,i);
			delay();
			}
		}
	}
}

