/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"STM32F407xx.h"
void USART1_init(){
	RCC->APB2ENR|=(1<<4);
	RCC->AHB1ENR|=(1<<0);
	RCC->AHB1ENR|=(1<<3);
	GPIOD->MODER&=~(3<<24);
	GPIOD->MODER|=(1<<24);
	//TX-PA9
	GPIOA->MODER&=~(3<<18);
	GPIOA->MODER|=(2<<18);

	GPIOA->AFR[1]&=~(0XF<<4);
	GPIOA->AFR[1]|=(7<<4);
	//RX-PA10
	GPIOA->MODER&=~(3<<20);
	GPIOA->MODER|=(2<<20);

	GPIOA->AFR[1]&=~(0XF<<8);
	GPIOA->AFR[1]|=(7<<8);

	USART1->BRR=0x0683;//9600
	USART1->CR1|=(1<<3);//enable TE
	USART1->CR1|=(1<<13);//enable usart

}
void USART1_write(uint8_t ch){
	while(!(USART1->SR&(1<<7)));//TXE
	USART1->DR=ch;
	while(!(USART1->SR & (1<<6)));
}
void USART1_write_string(const char *p){
	while(*p!='\0'){
		USART1_write(*p++);
	}
}
void delay(uint8_t time){
	while(time--){
		for(uint16_t i=0;i<100000;i++);
	}
}
int main(void)
{
    USART1_init();
    while(1){
    USART1_write_string("JAGADEESH\n\r");
    GPIOD->ODR^=(1<<12);
    delay(10);
    }
}
